### ISSUE TITLE
Error in model.linearize()

### ISSUE THREAD

**Issue by miwamasa** [jgoppert/pymola#5]
I have tried your example.

"model.linearize() "causses folloing error

have an idea?

```
AttributeError                            Traceback (most recent call last)
<ipython-input-13-62321030cd0e> in <module>()
----> 1 model.linearize()

C:\Applications\WinPython-64bit-2.7.9.4\python-2.7.9.amd64\lib\site-packages\pymola\sympy_runtime.pyc in linearize(self, x0, u0)
     59             u0 = self.x.subs(self.u0)[:]
     60         for i in range(len(ss)):
---> 61             ss_eval += [pl.matrix(ss[i].subs(ss_subs)).astype(float)]
     62         return ss_eval
     63 

AttributeError: 'module' object has no attribute 'matrix'

```

**Comment by miwamasa** [comment]
My pylab had been an old version (0.1.3)
After I installed new version, it seems working.

Great project!

**Comment by jgoppert** [comment]
Thanks!

**Comment by miwamasa** [comment]
Just for your information,

In my case, the pylab was wrong.  Matplotlib will also install pylab. It seems separatelly installing additional pylab causes problem. By unistalling pylab,  I got through it.

http://stackoverflow.com/questions/32279887/pylab-module-object-has-no-attribute-figure
