### ISSUE TITLE
sympy compiler broken

### ISSUE THREAD

**Issue by jgoppert** [jgoppert/pymola#7]
@jbaayen glad to get some help on this. I'm very interested in what you are doing with casadi. My toy sympy backend was pretty limited, but I'd like to work towards getting the unit tests for it passing again. It is pretty useful to demo the capabilities in the jupyter notebook with sympy. It would be nice to get some examples of jupyter notebooks with casadi as well.

I created a script to ease environment bring up, create_conda_env.sh, also I fixed some compiler warnings and helped speed it up a bit.  I was able to install gcc via conda, so hopefully this will also work for you.

**Comment by jgoppert** [comment]
I think this is because the state prefix was removed.

The comment  that you left suggests that you couldn't find a way to find the symbol if it was declared in a super class. This makes sense if we haven't flattened the class yet, but once it is flattened, it should be straightforward.

It seems your approach is to do some extra annotation in the generator, I think this is OK, but it would be nicer if we could have a flag in the AST that the state is differentiated somewhere. What do you think?

**Comment by jbaayen** [comment]
Thanks for merging our pull request! Glad you managed to get the sympy
stuff back online as well.

I'm about to create another pull request for some issues that were
introduced.
I also noticed that in the parser, you've changed exitDeclaration to always
set start attributes. I wonder if this is the best way. For our purposes,
we only want to have the start attribute set if the user set it explicitly.
Would there be a way to make the sympy notebook work without inferring
start attributes in the parser?

A casadi example notebook would be nice indeed. I'll see if I can come up
something later this or next week.

**Comment by jgoppert** [comment]
Currently I was using the start value to initialize my parameter dictionary. So I can switch it to use value if that would help. Somewhere in the Modelica spec I think it states that initial conditions are assumed to be zero if not specified. We will want to make sure we handle it in the same way the standard library expects us to.

Looking forward to the casadi notebook example.

**Comment by jbaayen** [comment]
Right, I see. It would be helpful from our perspective if you could switch the parameter dict to use the value field. We do the same.

Regarding initial conditions: It would still be great to be able to distinguish between initial conditions which the user explicitly specified, and inferred initial conditions. If only to give more weight to the user-specified ICs during initialization. 

As a general note, I would prefer the AST not to include too much 'magic' and rather leave that to the backends, or any middleware. In the longer term, it may be nice to have a bunch of middleware AST transformation classes that can be enabled or disabled using compiler options.
