### ISSUE TITLE
Casadi notebook example

### ISSUE THREAD

**Issue by jgoppert** [jgoppert/pymola#9]
I think the new casadi backend is great, but I don't know much about using it, would be great if we could add a demo notebook of how to use the existing Casadi model that is created to do simulation and jacobians of vector functions with respect to vector variables (A = df/dx, B = df/du, etc.). I copied the demo Casadi notebook and tried to get it running myself but found it confusing, see test/Casadi.ipynb.

@jbaayen

**Comment by jbaayen** [comment]
An example notebook has been added, showing how a Modelica model can be transferred to CasADi, and how CasADi can then be used to set up and solve optimal control problems for the model.

**Comment by jgoppert** [comment]
I appreciate it, hopefully I can test it out on some toy problems now.
